# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stream.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cstream.proto\"\x1c\n\x0bStreamFrame\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\" \n\rStreamRequest\x12\x0f\n\x07request\x18\x01 \x01(\x05\x32\x37\n\x06Stream\x12-\n\tDetection\x12\x0e.StreamRequest\x1a\x0c.StreamFrame\"\x00\x30\x01\x62\x06proto3'
)




_STREAMFRAME = _descriptor.Descriptor(
  name='StreamFrame',
  full_name='StreamFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame', full_name='StreamFrame.frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=44,
)


_STREAMREQUEST = _descriptor.Descriptor(
  name='StreamRequest',
  full_name='StreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='StreamRequest.request', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['StreamFrame'] = _STREAMFRAME
DESCRIPTOR.message_types_by_name['StreamRequest'] = _STREAMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StreamFrame = _reflection.GeneratedProtocolMessageType('StreamFrame', (_message.Message,), {
  'DESCRIPTOR' : _STREAMFRAME,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamFrame)
  })
_sym_db.RegisterMessage(StreamFrame)

StreamRequest = _reflection.GeneratedProtocolMessageType('StreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _STREAMREQUEST,
  '__module__' : 'stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamRequest)
  })
_sym_db.RegisterMessage(StreamRequest)



_STREAM = _descriptor.ServiceDescriptor(
  name='Stream',
  full_name='Stream',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=80,
  serialized_end=135,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detection',
    full_name='Stream.Detection',
    index=0,
    containing_service=None,
    input_type=_STREAMREQUEST,
    output_type=_STREAMFRAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAM)

DESCRIPTOR.services_by_name['Stream'] = _STREAM

# @@protoc_insertion_point(module_scope)
